apiVersion: apps/v1
kind: Deployment
metadata:
  name: view
  labels:
    app: view
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: view
  template:
    metadata:
      labels:
        app: view
        tier: view
    spec:
      containers:
      - name: view
        image: 20202299/view:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: view
---
apiVersion: v1
kind: Service
metadata:
  name: view
  labels:
    app: view
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: view
    tier: view
  type: LoadBalancer
