apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
  labels:
    app: service
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
        tier: service
    spec:
      containers:
      - name: service
        image: 20202299/service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: service
---
apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: service
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: service
    tier: service
  type: LoadBalancer
